blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/1419krusty/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Check the documentation for development and usage information
  - name: 💬 General Discussion
    url: https://github.com/1419krusty/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss ideas with the community