name: Feature Request
description: Request a new feature or enhancement for the school activities system
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - copilot

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand what you need and why it would be valuable.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: What new functionality would you like to see added?
      placeholder: "Example: Add a calendar view to show when activities meet throughout the week"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: What problem does this solve?
      description: Describe the challenge or need that this feature would address
      placeholder: "Example: Teachers and students need an easier way to see schedule conflicts and plan their time around multiple activities"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Example:
        - Add a calendar icon next to the current list view
        - Calendar should show all activities by day of the week
        - Students should be able to see their registered activities highlighted
        - Teachers should be able to see activities they supervise
    validations:
      required: true

  - type: dropdown
    id: user-benefit
    attributes:
      label: Who would benefit from this feature?
      description: Which users would find this feature helpful?
      options:
        - Students only
        - Teachers only
        - Both students and teachers
        - School administrators
        - All users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature?
      description: How would you prioritize this enhancement?
      options:
        - Nice to have - would be a small improvement
        - Useful - would make things noticeably easier
        - Important - would solve a significant problem
        - Essential - really needed for the system to work well
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other ways to solve this problem?
      placeholder: "Example: We could use external calendar apps, but having it built into the activities system would be more convenient"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other information that would help us implement this feature?
        - Examples from other systems you've seen
        - Screenshots or mockups if you have them
        - Related features that might work together
        - Technical considerations or constraints
      placeholder: "Add any additional details, examples, or context here"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: How will we know this feature is complete?
      description: What should this feature do when it's finished?
      placeholder: |
        - Teachers can view activities in a weekly calendar format
        - Students can see their registered activities highlighted
        - Calendar shows activity times and locations
        - Users can switch between list and calendar views easily
    validations:
      required: true

  - type: textarea
    id: implementation-hints
    attributes:
      label: Implementation Suggestions (Optional)
      description: Any technical hints or suggestions for how this might be built?
      placeholder: |
        Example suggestions:
        - Could use a JavaScript calendar library
        - Might need to add time fields to the activities data
        - Should integrate with existing filtering system